[package]
name = "lua-marshalling"
version = "0.1.0"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]

[dependencies]
libc = "0.2.20"
derive-lua-marshalling = { path = "../derive-lua-marshalling" }
