[package]
name = "derive-lua-marshalling"
version = "0.1.0"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]

[dependencies]
libc = "0.2.20"
syn = "0.11"
quote = "0.3"
derive-c-marshalling-library = { path = "../derive-c-marshalling-library" }

[lib]
proc-macro = true
